"use client";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, Loader2, X } from "lucide-react";
import { SharedEditor } from "@/components/editor-v2/SharedEditor";
import { DEFAULT_EDITOR_LANGUAGE, EditorLanguageChoice, EditorLayout } from "@/components/editor-v2/model";
import { studioVisualResolution } from "@/components/editor-v2/visualResolution";
import { EditorLanguageControl } from "@/components/editor-v2/EditorLanguageControl";
import { studioV2Api, studioV2PageTileURL, StudioEditorStateDTO, StudioJobDTO, StudioVDMDTO } from "@/lib/studio-v2/api";
import { editorCompileError, editorExtractionStartError, editorExtractionSubmissionFailure, editorExtractionView, shouldPollEditorExtraction } from "@/lib/studio-v2/editorExtractionState";

interface Props { sessionId: string; baseVersionId: string; documentName: string; vdm: StudioVDMDTO; newIdempotencyKey: (operation: string) => string; onBack: () => void; onCompiled: () => Promise<void> | void; }
const terminal = (job: StudioJobDTO) => ["succeeded", "failed", "cancelled"].includes(job.status);
const languageKey = (choice: EditorLanguageChoice) => `${choice.mode}:${choice.languages.join("+")}`;
const extractKey = (session: string, choice: EditorLanguageChoice) => `studio-v2-editor-extract:${session}:${languageKey(choice)}`;
const compileKey = (session: string, state: string) => `studio-v2-editor-compile:${session}:${state}`;

export const StudioV2EditWorkspace: React.FC<Props> = ({ sessionId, baseVersionId, documentName, vdm, newIdempotencyKey, onBack, onCompiled }) => {
  const [language, setLanguage] = useState<EditorLanguageChoice>(DEFAULT_EDITOR_LANGUAGE); const [job, setJob] = useState<StudioJobDTO | null>(null); const [state, setState] = useState<StudioEditorStateDTO | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState<string | null>(null); const [compileJob, setCompileJob] = useState<StudioJobDTO | null>(null); const [compileSubmitting, setCompileSubmitting] = useState(false); const [cancelSubmitting, setCancelSubmitting] = useState(false); const [dirty, setDirty] = useState(false); const extractStartedRef = useRef(false); const compileInFlightRef = useRef(false); const cancelInFlightRef = useRef(false);
  const changeLanguage = (next: EditorLanguageChoice) => { if (!dirty || window.confirm("Discard unsaved edits and extract again with this language?")) { setDirty(false); setLanguage(next); } };
  const loadState = useCallback(async (stateId: string) => { const response = await studioV2Api.getEditorState(sessionId, stateId); setState(response.editor_state); }, [sessionId]);
  const submitExtract = useCallback(async () => { if (extractStartedRef.current) return; extractStartedRef.current = true; try { const response = await studioV2Api.submitJob(sessionId, { base_version_id: baseVersionId, idempotency_key: newIdempotencyKey(`editor-extract-${languageKey(language)}`), operation: "editor_extract", parameters: { language_mode: language.mode, languages: language.languages } }); setJob(response.job); window.localStorage.setItem(extractKey(sessionId, language), response.job.id); } catch { const failure = editorExtractionSubmissionFailure(); extractStartedRef.current = false; setJob(failure.job); setError(failure.error); throw new Error(failure.error); } }, [baseVersionId, language, newIdempotencyKey, sessionId]);
  useEffect(() => { let cancelled = false; void (async () => { await Promise.resolve(); if (cancelled) return; setState(null); setJob(null); setError(null); setBusy(true); extractStartedRef.current = false; try { const saved = window.localStorage.getItem(extractKey(sessionId, language)); if (saved) { const response = await studioV2Api.getJob(sessionId, saved); if (!cancelled && response.job.status === "succeeded" && response.job.editor_state_id) await loadState(response.job.editor_state_id); else if (!cancelled && !terminal(response.job)) setJob(response.job); else if (!cancelled) await submitExtract(); } else await submitExtract(); } catch { if (!cancelled) setError(editorExtractionStartError); } })().finally(() => { if (!cancelled) setBusy(false); }); return () => { cancelled = true; }; }, [language, loadState, sessionId, submitExtract]);
  useEffect(() => { if (!job || !shouldPollEditorExtraction(job, Boolean(state))) return; let cancelled = false; let timer = 0; const poll = async () => { try { const response = await studioV2Api.getJob(sessionId, job.id); if (cancelled) return; setJob(response.job); if (response.job.status === "succeeded" && response.job.editor_state_id) { window.localStorage.removeItem(extractKey(sessionId, language)); await loadState(response.job.editor_state_id); } else if (terminal(response.job)) setError(response.job.error_code === "LANGUAGE_REQUIRED" ? "Automatic language detection was uncertain. Choose English, Sinhala, or Tamil and retry." : response.job.error || "Editor extraction did not complete."); else timer = window.setTimeout(() => void poll(), 800); } catch (err) { if (!cancelled) setError(err instanceof Error ? err.message : "Unable to poll extraction."); } }; void poll(); return () => { cancelled = true; window.clearTimeout(timer); }; }, [job, language, loadState, sessionId, state]);
  const retryExtract = useCallback(() => { if (busy || (job && !terminal(job))) return; window.localStorage.removeItem(extractKey(sessionId, language)); extractStartedRef.current = false; setJob(null); setError(null); setBusy(true); void submitExtract().catch(() => undefined).finally(() => setBusy(false)); }, [busy, job, language, sessionId, submitExtract]);
  const compile = async (layout: EditorLayout) => { if (!state || compileInFlightRef.current) return; compileInFlightRef.current = true; setCompileSubmitting(true); setError(null); try { const response = await studioV2Api.submitJob(sessionId, { base_version_id: state.base_version_id, idempotency_key: newIdempotencyKey("editor-compile"), operation: "editor_compile", parameters: { editor_state_id: state.id, layout } }); setCompileJob(response.job); window.localStorage.setItem(compileKey(sessionId, state.id), response.job.id); } catch { setError(editorCompileError); } finally { compileInFlightRef.current = false; setCompileSubmitting(false); } };
  useEffect(() => { if (!compileJob || terminal(compileJob)) return; let cancelled = false; let timer = 0; const poll = async () => { try { const response = await studioV2Api.getJob(sessionId, compileJob.id); if (cancelled) return; setCompileJob(response.job); if (response.job.status === "succeeded") { window.localStorage.removeItem(compileKey(sessionId, state?.id ?? "")); await onCompiled(); } else if (terminal(response.job)) setError(editorCompileError); else timer = window.setTimeout(() => void poll(), 800); } catch { if (!cancelled) setError(editorCompileError); } }; void poll(); return () => { cancelled = true; window.clearTimeout(timer); }; }, [compileJob, onCompiled, sessionId, state?.id]);
  useEffect(() => { if (!state || compileJob) return; const saved = window.localStorage.getItem(compileKey(sessionId, state.id)); if (!saved) return; let cancelled = false; void studioV2Api.getJob(sessionId, saved).then(async (response) => { if (cancelled) return; if (response.job.status === "succeeded") { window.localStorage.removeItem(compileKey(sessionId, state.id)); await onCompiled(); } else setCompileJob(response.job); }).catch(() => { if (!cancelled) setError(editorCompileError); }); return () => { cancelled = true; }; }, [compileJob, onCompiled, sessionId, state]);
  const cancelJob = async (target: StudioJobDTO | null) => { if (!target || terminal(target) || cancelInFlightRef.current) return; cancelInFlightRef.current = true; setCancelSubmitting(true); try { const response = await studioV2Api.cancelJob(sessionId, target.id); if (target.id === job?.id) setJob(response.job); else setCompileJob(response.job); } finally { cancelInFlightRef.current = false; setCancelSubmitting(false); } };
  const extractionView = editorExtractionView({ busy, hasJob: Boolean(job), hasState: Boolean(state), error }); const compileBusy = Boolean(compileJob && !terminal(compileJob));
  return <main className="flex h-screen w-screen flex-col overflow-hidden bg-[#0B0C0F] text-[#F5F7FA]" data-testid="studio-edit-workspace"><header className="flex min-h-14 items-center justify-between border-b border-[#292D35] px-4"><div className="flex items-center gap-3"><button aria-label="Back to Studio" onClick={() => { if (!dirty || window.confirm("Discard unsaved edits?")) onBack(); }}><ArrowLeft/></button><div><h1 className="text-sm font-semibold">Edit PDF</h1><p className="text-[10px] text-[#9AA1AD]">{documentName} · shared Editor V2</p></div></div><div className="flex items-center gap-3"><EditorLanguageControl value={language} onChange={changeLanguage} disabled={Boolean(job && !terminal(job))}/><span role="status" aria-live="polite" className="text-xs text-[#9AA1AD]">{compileJob?.message || job?.message || (state ? "Ready to edit" : "Extracting…")}</span>{((job && !terminal(job)) || compileBusy) && <button aria-label="Cancel editor job" onClick={() => void cancelJob(compileBusy ? compileJob : job)} disabled={cancelSubmitting}><X className="inline"/>{cancelSubmitting ? "Cancelling…" : "Cancel"}</button>}</div></header>{error && <div role="alert" className="border-b border-red-400/30 bg-red-950/40 px-4 py-2 text-xs text-red-200">{error}</div>}{!state ? <section className="flex flex-1 flex-col items-center justify-center gap-3">{extractionView === "failure" ? <><p>{error || editorExtractionStartError}</p><button data-testid="studio-editor-extraction-retry" onClick={retryExtract}>Retry extraction</button></> : <><Loader2 className="animate-spin"/><p>Extracting editor layout… {job?.progress ?? 0}%</p></>}</section> : <section className="flex min-h-0 flex-1 p-4"><SharedEditor baseline={state.layout} renderPageVisual={(index, visual) => { const descriptor = vdm.pages[index]; const page = state.layout.pages[index]; if (!descriptor || !page) return null; const resolution = studioVisualResolution({ pageWidthPt: page.width, zoom: visual.zoom, devicePixelRatio: visual.devicePixelRatio }); return <img src={studioV2PageTileURL(sessionId, baseVersionId, descriptor.page_id, resolution.scale)} alt={`Page ${index + 1}`} className="h-full w-full object-fill" draggable={false}/>; }} onCompile={compile} compiling={compileSubmitting || compileBusy} showPageSidebar onDirtyChange={setDirty}/></section>}</main>;
};
