"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import {
    ArrowLeft,
    Download,
    Check,
    Copy,
    FolderTree,
    Cpu,
    Boxes,
    Terminal,
    KeyRound,
    Network,
    TestTube2,
    Rocket,
    GitBranch,
    Eye,
    Clock,
    CheckCircle2,
    Layers,
    GitFork,
    Flame,
    Activity,
} from "lucide-react";
import { useSharedTool } from "@/app/(site)/[toolId]/ClientToolLayout";
import {
    useRepositoryAnalyzer,
    ALL_REPORTS,
} from "@/context/RepositoryAnalyzerContext";
import RepositoryMapExplorer from "./explorers/RepositoryMapExplorer";
import ArchitectureExplorer from "./explorers/ArchitectureExplorer";
import FlowExplorer from "./explorers/FlowExplorer";
import ImpactExplorer from "./explorers/ImpactExplorer";
import HotspotExplorer from "./explorers/HotspotExplorer";
import EvidenceExplorer from "./explorers/EvidenceExplorer";
import RepositoryAnalyzerArchitectureSummary from "./RepositoryAnalyzerArchitectureSummary";
import { Evidence } from "@/types/analyzer";
import { normalizeCanonicalAnalysisResult } from "@/lib/analyzer/normalize";

export default function RepositoryAnalyzerDownload() {
    const router = useRouter();
    const { toolId, setFile } = useSharedTool();
    const {
        source,
        result,
        enableAi,
        evidenceModalTech,
        openEvidenceModal,
        closeEvidenceModal,
        reset,
    } = useRepositoryAnalyzer();

    const [activeTab, setActiveTab] = useState<string>("Project Structure");
    const [activeExplorerTab, setActiveExplorerTab] = useState<"topology" | "flow" | "impact" | "hotspot">("topology");
    const [copiedIndex, setCopiedIndex] = useState<string | null>(null);

    // Empty state guard if accessed directly without result
    if (!result || !source) {
        return (
            <div className="mx-auto max-w-lg px-4 py-16 text-center">
                <div className="mx-auto inline-flex h-16 w-16 items-center justify-center rounded-3xl bg-[var(--primary)]/10 text-[var(--primary)]">
                    <GitBranch size={32} />
                </div>
                <h3 className="mt-6 text-xl font-bold text-[color:var(--foreground)]">
                    No analysis results available
                </h3>
                <p className="mt-2 text-sm text-[color:var(--muted-foreground)]">
                    Please select a project repository and run the analysis first.
                </p>
                <button
                    type="button"
                    onClick={() => {
                        setFile(null);
                        reset();
                        router.push(`/${toolId}`);
                    }}
                    className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-6 py-3 text-sm font-semibold text-white shadow-md transition hover:brightness-105"
                >
                    <ArrowLeft size={16} />
                    Start Analysis
                </button>
            </div>
        );
    }

    const reportIcons: Record<string, React.ReactNode> = {
        "Project Structure": <FolderTree size={18} className="text-blue-500" />,
        "Technology Stack": <Cpu size={18} className="text-indigo-500" />,
        "Dependencies": <Boxes size={18} className="text-emerald-500" />,
        "Setup & Run Guide": <Terminal size={18} className="text-amber-500" />,
        "Environment Configuration": <KeyRound size={18} className="text-purple-500" />,
        "API Overview": <Network size={18} className="text-cyan-500" />,
        "Testing": <TestTube2 size={18} className="text-rose-500" />,
        "Deployment": <Rocket size={18} className="text-orange-500" />,
    };

    const copyText = (text: string, id: string) => {
        navigator.clipboard.writeText(text);
        setCopiedIndex(id);
        setTimeout(() => setCopiedIndex(null), 2000);
    };

    // Generate comprehensive Markdown from canonical result
    const generateMarkdown = (): string => {
        const res = normalizeCanonicalAnalysisResult(result);
        const repoName = res.repository.name || "Repository";
        let md = `# Architecture Analysis Report: ${repoName}\n\n`;
        md += `> Generated by PDFNest Repository Analyzer (Engine: \`${res.provenance.engine}\` v${res.provenance.engineVersion})\n\n`;

        // Section 1: Executive Summary
        md += `## 1. Executive Summary\n\n`;
        md += `- **Repository Name:** \`${repoName}\`\n`;
        md += `- **Analysis Timestamp:** \`${new Date(res.createdAt).toUTCString()}\`\n`;
        md += `- **Complexity Tier:** \`${res.provenance.complexityTier}\` (Score: ${res.provenance.complexityScore})\n`;
        md += `- **Analysis Duration:** ${res.provenance.durationMs} ms\n`;
        if (res.intelligence?.scorecard) {
            md += `- **Overall Architecture Grade:** \`Grade ${res.intelligence.scorecard.overallGrade}\` (Score: ${res.intelligence.scorecard.overallScore.toFixed(1)}/100)\n`;
        }
        if (res.metrics.languages && res.metrics.languages.length > 0) {
            md += `- **Primary Languages:** ${res.metrics.languages.map(l => `${l.name} (${l.percentage.toFixed(1)}%)`).join(", ")}\n`;
        }
        const aiSummary = res.ai || res.architectureSummary;
        if (aiSummary?.summary) {
            md += `\n**AI Synthesis:** ${aiSummary.summary}\n`;
        }
        md += `\n`;

        // Section 2: Repository Overview
        md += `## 2. Repository Overview\n\n`;
        md += `| Metric | Value |\n|---|---|\n`;
        md += `| Total Discovered Files | ${res.metrics.totalFiles} |\n`;
        md += `| Included Files Analyzed | ${res.metrics.includedFiles} |\n`;
        md += `| Excluded Files | ${res.metrics.excludedFiles} |\n`;
        md += `| Total File Size | ${(res.metrics.totalBytes / (1024 * 1024)).toFixed(2)} MB (${res.metrics.totalBytes} bytes) |\n`;
        if (res.metrics.linesOfCode) {
            md += `| Estimated Lines of Code | ${res.metrics.linesOfCode} |\n`;
        }
        if (res.repository.defaultBranch) {
            md += `| Default Branch | \`${res.repository.defaultBranch}\` |\n`;
        }
        if (res.repository.commitHash) {
            md += `| Commit Hash | \`${res.repository.commitHash}\` |\n`;
        }
        md += `| Runtime Dependencies | ${res.dependencies.runtime.length} |\n`;
        md += `| Development Dependencies | ${res.dependencies.development.length} |\n`;
        md += `| Static API Routes | ${res.routes.length} |\n\n`;

        // Section 3: Project Structure
        md += `## 3. Project Structure\n\n`;
        if (res.structure) {
            md += `Structured inventory contains **${res.structure.totalDirs}** directories and **${res.structure.totalFiles}** files.\n\n`;
        }
        if (res.structureTree) {
            md += `\`\`\`text\n${res.structureTree}\n\`\`\`\n\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 4: Technology Stack
        md += `## 4. Technology Stack\n\n`;
        if (res.technologies.length === 0) {
            md += `No findings were produced by this analyzer.\n\n`;
        } else {
            md += `| Technology | Category | Confidence | Version | Negative Assertions Passed |\n|---|---|---|---|---|\n`;
            res.technologies.forEach((t) => {
                const ver = t.version ? `\`${t.version}\`` : "-";
                const neg = t.negativeAssertionsPassed && t.negativeAssertionsPassed.length > 0 ? t.negativeAssertionsPassed.join(", ") : "-";
                md += `| **${t.name}** | ${t.category} | \`${t.confidence}\` | ${ver} | ${neg} |\n`;
            });
            md += `\n`;
        }

        // Section 5: Architecture / System Topology
        md += `## 5. Architecture / System Topology\n\n`;
        const archList = res.intelligence?.architecture || [];
        if (archList.length > 0) {
            md += `| Tier | Entity ID | Epistemic Confidence | Evidence Count |\n|---|---|---|---|\n`;
            archList.forEach((comp) => {
                md += `| **${comp.tier}** | \`${comp.entityId}\` | \`${comp.confidence}\` | ${comp.evidence?.length || 0} |\n`;
            });
            md += `\n`;
        } else if (res.deployment.dockerAvailable || res.routes.length > 0) {
            md += `- **API Layer:** Detected REST/HTTP endpoints and service controllers.\n`;
            if (res.deployment.dockerAvailable) {
                md += `- **Containerization / Deployment:** Docker container deployment enabled.\n`;
            }
            md += `\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 6: Entities
        md += `## 6. Entities\n\n`;
        const entities = res.graph?.entities || [];
        if (entities.length > 0) {
            md += `Total canonical entities extracted: **${entities.length}**\n\n`;
            md += `| Entity ID | Kind | Name | Relative Path |\n|---|---|---|---|\n`;
            const limit = Math.min(entities.length, 40);
            for (let i = 0; i < limit; i++) {
                const e = entities[i];
                md += `| \`${e.id}\` | \`${e.kind}\` | \`${e.name}\` | \`${e.path || "-"}\` |\n`;
            }
            if (entities.length > limit) {
                md += `\n*(Showing ${limit} of ${entities.length} canonical entities)*\n`;
            }
            md += `\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 7: Relationship Graph
        md += `## 7. Relationship Graph\n\n`;
        const gm = res.graphMetrics;
        if (gm) {
            md += `| Graph Metric | Value |\n|---|---|\n`;
            md += `| Total Nodes (Entities) | ${gm.entityCount} |\n`;
            md += `| Total Edges (Relationships) | ${gm.edgeCount} |\n`;
            md += `| Confirmed Edges | ${gm.confirmedEdgeCount} |\n`;
            md += `| Inferred Edges | ${gm.inferredEdgeCount} |\n`;
            md += `| Evidence Coverage | ${gm.evidenceCoveragePct.toFixed(1)}% |\n`;
            md += `| Dependency Cycles | ${gm.cycleCount} |\n`;
            md += `| Orphan Entities | ${gm.orphanEntityCount} |\n`;
            md += `| Unresolved References | ${gm.unresolvedReferences} |\n\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 8: Execution Flows
        md += `## 8. Execution Flows\n\n`;
        const flowList = res.intelligence?.flow || [];
        if (flowList.length > 0) {
            flowList.forEach((flow, idx) => {
                md += `### Flow ${idx + 1}: \`${flow.id}\`\n\n`;
                flow.steps.forEach((step) => {
                    md += `- **${step.action}**: \`${step.entityId}\` → \`${step.targetId}\` *(Confidence: \`${step.confidence}\`)*\n`;
                });
                md += `\n`;
            });
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 9: API / Entry Points
        md += `## 9. API / Entry Points\n\n`;
        if (res.routes.length === 0) {
            md += `No findings were produced by this analyzer.\n\n`;
        } else {
            md += `| Method | Endpoint Path | Inferred Handler | Auth Required | Source File |\n|---|---|---|---|---|\n`;
            res.routes.forEach((r) => {
                const sf = r.lineNumber ? `${r.sourceFile}:${r.lineNumber}` : r.sourceFile;
                md += `| **${r.method}** | \`${r.path}\` | \`${r.inferredHandler || "inline"}\` | ${r.authRequired ? "Yes" : "No"} | \`${sf}\` |\n`;
            });
            md += `\n`;
        }

        // Section 10: Change Impact Analysis
        md += `## 10. Change Impact Analysis\n\n`;
        const impactMap = res.intelligence?.impact || {};
        const impactEntries = Object.entries(impactMap);
        if (impactEntries.length > 0) {
            md += `| Target Entity | Blast Radius (Direct / Indirect) | Affected Routes | Affected Services | Risk Score |\n|---|---|---|---|---|\n`;
            impactEntries.forEach(([entId, imp]) => {
                md += `| \`${entId}\` | ${imp.directDependents} direct / ${imp.indirectDependents} indirect | ${imp.affectedRoutes} | ${imp.affectedServices} | \`${imp.riskScore}\` |\n`;
            });
            md += `\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 11: Engineering Hotspots
        md += `## 11. Engineering Hotspots\n\n`;
        const hotspotList = res.intelligence?.hotspots || [];
        if (hotspotList.length > 0) {
            md += `| Entity | Fan-In | Fan-Out | Centrality | Complexity | Tested | Hotspot Metric |\n|---|---|---|---|---|---|---|\n`;
            hotspotList.forEach((hs) => {
                md += `| \`${hs.entityId}\` | ${hs.fanIn} | ${hs.fanOut} | ${hs.centrality.toFixed(2)} | ${hs.complexity.toFixed(1)} | ${hs.isTested ? "YES" : "NO"} | **${hs.hotspotMetric.toFixed(1)}** |\n`;
            });
            md += `\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 12: Security Findings
        md += `## 12. Security Findings\n\n`;
        const secList = res.intelligence?.security || [];
        if (secList.length > 0) {
            secList.forEach((sec) => {
                md += `### [${sec.severity}] ${sec.title} (\`${sec.ruleId}\`)\n\n`;
                md += `- **Location:** \`${sec.entityId}\`\n`;
                md += `- **Description:** ${sec.description}\n`;
                if (sec.remediation) {
                    md += `- **Remediation:** ${sec.remediation}\n`;
                }
                md += `- **Confidence:** \`${sec.confidence}\`\n\n`;
            });
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 13: Test Intelligence
        md += `## 13. Test Intelligence\n\n`;
        const testIntel = res.intelligence?.test;
        if (testIntel && (testIntel.untestedComponents.length > 0 || testIntel.mappings.length > 0)) {
            if (testIntel.untestedComponents.length > 0) {
                md += `### High-FanIn Untested Components\n\n`;
                md += `| Component | Kind | Fan-In |\n|---|---|---|\n`;
                testIntel.untestedComponents.forEach((uc) => {
                    md += `| \`${uc.name}\` | \`${uc.kind}\` | ${uc.fanIn} |\n`;
                });
                md += `\n`;
            }
            if (testIntel.mappings.length > 0) {
                md += `### Test Mappings\n\n`;
                testIntel.mappings.forEach((tm) => {
                    md += `- **${tm.entityName}**: Tests: \`${tm.testFiles.join("`, `")}\`\n`;
                });
                md += `\n`;
            }
        } else if (res.testing.frameworks.length > 0) {
            md += `- **Frameworks:** ${res.testing.frameworks.join(", ")}\n\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 14: Architecture Scorecard
        md += `## 14. Architecture Scorecard\n\n`;
        const scorecard = res.intelligence?.scorecard;
        if (scorecard) {
            md += `**Overall Quality Grade:** \`Grade ${scorecard.overallGrade}\` (Score: **${scorecard.overallScore.toFixed(1)}/100**)\n\n`;
            if (scorecard.components && scorecard.components.length > 0) {
                md += `| Component | Grade | Score | Rationale |\n|---|---|---|---|\n`;
                scorecard.components.forEach((comp) => {
                    md += `| **${comp.component}** | \`${comp.grade}\` | ${comp.score.toFixed(0)}% | ${comp.rationale} |\n`;
                });
                md += `\n`;
            }
            if (scorecard.recommendations && scorecard.recommendations.length > 0) {
                md += `### Prioritized Recommendations\n\n`;
                scorecard.recommendations.forEach((rec) => {
                    md += `- **[${rec.priority.toUpperCase()}] ${rec.title}**: ${rec.description}\n`;
                });
                md += `\n`;
            }
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 15: Evidence & Provenance
        md += `## 15. Evidence & Provenance\n\n`;
        md += `### Engine Provenance\n\n`;
        md += `- **Engine:** \`${res.provenance.engine}\` (v${res.provenance.engineVersion})\n`;
        md += `- **Rules Evaluated:** ${res.provenance.rulesEvaluatedCount}\n`;
        md += `- **Complexity Tier:** \`${res.provenance.complexityTier}\` (Score: ${res.provenance.complexityScore})\n`;
        if (res.provenance.sourceArtifactSha256) {
            md += `- **Source Artifact SHA-256:** \`${res.provenance.sourceArtifactSha256}\`\n`;
        }
        md += `\n`;

        const evList = res.evidence || [];
        if (evList.length > 0) {
            md += `### Canonical Evidence Catalog (${evList.length} items)\n\n`;
            md += `| Evidence ID | Source | File Path | Lines | Detector | Confidence | Description |\n|---|---|---|---|---|---|---|\n`;
            const limit = Math.min(evList.length, 40);
            for (let i = 0; i < limit; i++) {
                const ev = evList[i];
                let lines = "-";
                if (ev.lineStart != null) {
                    lines = ev.lineEnd != null && ev.lineEnd !== ev.lineStart ? `${ev.lineStart}-${ev.lineEnd}` : `${ev.lineStart}`;
                }
                md += `| \`${ev.id}\` | \`${ev.sourceType}\` | \`${ev.filePath}\` | ${lines} | \`${ev.detector}\` | \`${ev.confidence}\` | ${ev.description} |\n`;
            }
            if (evList.length > limit) {
                md += `\n*(Showing ${limit} of ${evList.length} canonical evidence records)*\n`;
            }
            md += `\n`;
        } else {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 16: Environment / Deployment
        md += `## 16. Environment / Deployment\n\n`;
        if (res.environment.variables.length > 0) {
            md += `### Environment Variables\n\n`;
            md += `| Variable | Inferred Type | Required | Source |\n|---|---|---|---|\n`;
            res.environment.variables.forEach((v) => {
                md += `| \`${v.name}\` | \`${v.inferredType}\` | ${v.required ? "Yes" : "No"} | \`${v.source}\` |\n`;
            });
            md += `\n`;
        }
        md += `- **Docker Available:** ${res.deployment.dockerAvailable ? "Yes" : "No"}\n`;
        if (res.deployment.dockerfilePaths.length > 0) {
            md += `- **Dockerfiles:** \`${res.deployment.dockerfilePaths.join("`, `")}\`\n`;
        }
        if (res.deployment.composePaths.length > 0) {
            md += `- **Docker Compose Files:** \`${res.deployment.composePaths.join("`, `")}\`\n`;
        }
        if (res.deployment.ciWorkflows.length > 0) {
            md += `- **CI Workflows:**\n`;
            res.deployment.ciWorkflows.forEach((w) => {
                md += `  - \`${w.name || w.path}\`\n`;
            });
        }
        md += `\n`;

        // Section 17: Dependencies
        md += `## 17. Dependencies\n\n`;
        if (res.dependencies.runtime.length > 0) {
            md += `### Runtime Dependencies\n\n`;
            res.dependencies.runtime.forEach((d) => {
                md += `- \`${d.name}\` (${d.version}) [${d.manager}]\n`;
            });
            md += `\n`;
        }
        if (res.dependencies.development.length > 0) {
            md += `### Development Dependencies\n\n`;
            res.dependencies.development.forEach((d) => {
                md += `- \`${d.name}\` (${d.version}) [${d.manager}]\n`;
            });
            md += `\n`;
        }
        if (res.dependencies.runtime.length === 0 && res.dependencies.development.length === 0) {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 18: Testing
        md += `## 18. Testing\n\n`;
        if (res.testing.frameworks.length > 0) {
            md += `- **Frameworks:** ${res.testing.frameworks.join(", ")}\n`;
        }
        if (res.testing.testCommands.length > 0) {
            md += `### Test Execution Commands\n\n\`\`\`bash\n`;
            res.testing.testCommands.forEach((cmd) => {
                md += `${cmd}\n`;
            });
            md += `\`\`\`\n\n`;
        }
        if (res.testing.frameworks.length === 0 && res.testing.testCommands.length === 0) {
            md += `No findings were produced by this analyzer.\n\n`;
        }

        // Section 19: Limitations / Confidence
        md += `## 19. Limitations / Confidence\n\n`;
        md += `- **Epistemic Confidence Framework:** Findings are strictly tagged as \`CONFIRMED\` (directly proven by manifests/AST), \`STRONGLY_INFERRED\` (high-confidence heuristic matches), or \`WEAKLY_INFERRED\` (indirect signal).\n`;
        md += `- **Deterministic Analysis:** Analysis is 100% reproducible and operates fail-closed on local repository source trees.\n`;
        md += `- **Language Resolution Boundary:** Go, TypeScript, JavaScript, Python, Rust, and Dockerfiles are supported with native AST and manifest extractors.\n`;

        return md;
    };

    const downloadMarkdown = () => {
        const md = generateMarkdown();
        const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${result.repository.name}-architecture-report.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    };

    return (
        <div className="mx-auto max-w-5xl space-y-8 px-4 py-6">
            {/* Step Progress Bar */}
            <div className="flex items-center justify-center">
                <nav aria-label="Progress" className="flex items-center gap-2 rounded-full border border-[color:var(--border)] bg-[var(--card)] px-4 py-1.5 text-xs font-semibold">
                    <span className="text-[color:var(--muted-foreground)]">1 Source</span>
                    <span className="text-[color:var(--border)]">/</span>
                    <span className="text-[color:var(--muted-foreground)]">2 Scoping</span>
                    <span className="text-[color:var(--border)]">/</span>
                    <span className="flex items-center gap-1 text-[var(--primary)] font-bold">
                        <span className="flex h-4 w-4 items-center justify-center rounded-full bg-[var(--primary)] text-[10px] text-white">3</span>
                        Documentation
                    </span>
                </nav>
            </div>

            {/* Header & Provenance Card */}
            <div className="rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm space-y-4">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex items-center gap-4">
                        <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-500">
                            <CheckCircle2 size={24} />
                        </div>
                        <div>
                            <div className="flex items-center gap-2">
                                <h1 className="text-xl font-bold text-[color:var(--foreground)] sm:text-2xl">
                                    {result.repository.name}
                                </h1>
                                <span className="rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
                                    Analysis Complete
                                </span>
                            </div>
                            <p className="mt-1 text-xs text-[color:var(--muted-foreground)] flex items-center gap-2">
                                <span>Tier: {result.provenance.complexityTier}</span>
                                <span>•</span>
                                <span className="flex items-center gap-1">
                                    <Clock size={12} />
                                    {result.provenance.durationMs}ms
                                </span>
                                <span>•</span>
                                <span>{result.metrics.totalFiles} files</span>
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-3">
                        <button
                            type="button"
                            onClick={downloadMarkdown}
                            className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-xs font-semibold text-white shadow-sm transition hover:brightness-105"
                        >
                            <Download size={14} />
                            Export Markdown
                        </button>
                        <button
                            type="button"
                            onClick={() => {
                                setFile(null);
                                reset();
                                router.push(`/${toolId}`);
                            }}
                            className="inline-flex items-center gap-1.5 rounded-xl border border-[color:var(--border)] bg-[var(--background)] px-3.5 py-2.5 text-xs font-semibold text-[color:var(--muted-foreground)] hover:bg-[var(--accent)] hover:text-[color:var(--foreground)]"
                        >
                            <ArrowLeft size={14} />
                            New Analysis
                        </button>
                    </div>
                </div>
            </div>

            {/* AI Architecture Synthesis */}
            <RepositoryAnalyzerArchitectureSummary
                summary={result.ai || result.architectureSummary}
                aiRequested={enableAi}
            />

            {/* Interactive Relationship & Intelligence Explorers */}
            <div className="rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm space-y-6">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[color:var(--border)] pb-4">
                    <div>
                        <h2 className="text-base font-bold text-[color:var(--foreground)]">
                            Interactive Architecture Explorers
                        </h2>
                        <p className="text-xs text-[color:var(--muted-foreground)]">
                            Explore semantic relationship graphs, blast radius, execution flows, and engineering hotspots.
                        </p>
                    </div>
                    <div className="flex items-center gap-1.5 p-1 rounded-xl bg-[var(--background)] border border-[color:var(--border)] overflow-x-auto">
                        <button
                            type="button"
                            onClick={() => setActiveExplorerTab("topology")}
                            className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold whitespace-nowrap transition ${
                                activeExplorerTab === "topology"
                                    ? "bg-[var(--primary)] text-white shadow-xs"
                                    : "text-[color:var(--muted-foreground)] hover:text-[color:var(--foreground)]"
                            }`}
                        >
                            <Layers size={14} />
                            Topology
                        </button>
                        <button
                            type="button"
                            onClick={() => setActiveExplorerTab("flow")}
                            className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold whitespace-nowrap transition ${
                                activeExplorerTab === "flow"
                                    ? "bg-[var(--primary)] text-white shadow-xs"
                                    : "text-[color:var(--muted-foreground)] hover:text-[color:var(--foreground)]"
                            }`}
                        >
                            <Activity size={14} />
                            Flows
                        </button>
                        <button
                            type="button"
                            onClick={() => setActiveExplorerTab("impact")}
                            className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold whitespace-nowrap transition ${
                                activeExplorerTab === "impact"
                                    ? "bg-[var(--primary)] text-white shadow-xs"
                                    : "text-[color:var(--muted-foreground)] hover:text-[color:var(--foreground)]"
                            }`}
                        >
                            <GitFork size={14} />
                            Change Impact
                        </button>
                        <button
                            type="button"
                            onClick={() => setActiveExplorerTab("hotspot")}
                            className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold whitespace-nowrap transition ${
                                activeExplorerTab === "hotspot"
                                    ? "bg-[var(--primary)] text-white shadow-xs"
                                    : "text-[color:var(--muted-foreground)] hover:text-[color:var(--foreground)]"
                            }`}
                        >
                            <Flame size={14} />
                            Hotspots & Scorecard
                        </button>
                    </div>
                </div>

                {activeExplorerTab === "topology" && <ArchitectureExplorer result={result} />}
                {activeExplorerTab === "flow" && <FlowExplorer result={result} />}
                {activeExplorerTab === "impact" && <ImpactExplorer result={result} />}
                {activeExplorerTab === "hotspot" && <HotspotExplorer result={result} />}
            </div>

            {/* 8 Documentation Domain Tabs */}
            <div className="rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm space-y-6">
                {/* Tab Navigation */}
                <div className="flex overflow-x-auto border-b border-[color:var(--border)] pb-3 gap-2">
                    {ALL_REPORTS.map((r) => {
                        const isActive = activeTab === r.id;
                        return (
                            <button
                                key={r.id}
                                type="button"
                                onClick={() => setActiveTab(r.id)}
                                className={`inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-xs font-semibold whitespace-nowrap transition ${
                                    isActive
                                        ? "bg-[var(--primary)] text-white shadow-xs"
                                        : "text-[color:var(--muted-foreground)] hover:bg-[var(--accent)] hover:text-[color:var(--foreground)]"
                                }`}
                            >
                                {reportIcons[r.id]}
                                {r.title}
                            </button>
                        );
                    })}
                </div>

                {/* Tab Content 1: Project Structure */}
                {activeTab === "Project Structure" && (
                    <div className="space-y-6">
                        <div className="flex items-center justify-between">
                            <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                                Directory Hierarchy & Filesystem Layout
                            </h3>
                            <button
                                type="button"
                                onClick={() => copyText(result.structureTree, "tree")}
                                className="inline-flex items-center gap-1 text-xs font-semibold text-[var(--primary)] hover:underline"
                            >
                                {copiedIndex === "tree" ? <Check size={14} /> : <Copy size={14} />}
                                {copiedIndex === "tree" ? "Copied" : "Copy Tree"}
                            </button>
                        </div>

                        <div className="h-[500px]">
                            <RepositoryMapExplorer result={result} />
                        </div>

                        {/* Language Distribution Breakdown */}
                        {result.metrics.languages.length > 0 && (
                            <div className="space-y-3 pt-2">
                                <h4 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Language Distribution
                                </h4>
                                <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                                    {result.metrics.languages.map((l) => (
                                        <div
                                            key={l.name}
                                            className="rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-3 text-center"
                                        >
                                            <p className="text-xs font-bold text-[color:var(--foreground)]">{l.name}</p>
                                            <p className="mt-1 text-lg font-extrabold text-[var(--primary)]">
                                                {l.percentage.toFixed(1)}%
                                            </p>
                                            <p className="text-[10px] text-[color:var(--muted-foreground)]">
                                                {l.fileCount} files ({Math.round(l.bytes / 1024)} KB)
                                            </p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 2: Technology Stack */}
                {activeTab === "Technology Stack" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Evidence-Based Technology Detection ({result.technologies.length})
                        </h3>

                        {result.technologies.length === 0 ? (
                            <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                No specific technologies or frameworks detected.
                            </p>
                        ) : (
                            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
                                {result.technologies.map((tech) => (
                                    <div
                                        key={tech.id}
                                        className="flex flex-col justify-between rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-3"
                                    >
                                        <div>
                                            <div className="flex items-center justify-between">
                                                <h4 className="text-sm font-bold text-[color:var(--foreground)]">
                                                    {tech.name}
                                                </h4>
                                                <span className="rounded-full bg-[var(--primary)]/10 px-2 py-0.5 text-[10px] font-bold text-[var(--primary)] uppercase">
                                                    {tech.confidence}
                                                </span>
                                            </div>
                                            <p className="text-[11px] text-[color:var(--muted-foreground)] capitalize mt-0.5">
                                                {tech.category} {tech.version ? `• v${tech.version}` : ""}
                                            </p>
                                        </div>

                                        {tech.negativeAssertionsPassed && tech.negativeAssertionsPassed.length > 0 && (
                                            <div className="text-[10px] text-emerald-600 dark:text-emerald-400">
                                                ✓ Negated: {tech.negativeAssertionsPassed.join(", ")}
                                            </div>
                                        )}

                                        <button
                                            type="button"
                                            onClick={() => openEvidenceModal(tech)}
                                            className="inline-flex items-center justify-center gap-1 rounded-xl border border-[color:var(--border)] bg-[var(--card)] py-1.5 text-xs font-semibold text-[color:var(--foreground)] hover:bg-[var(--accent)]"
                                        >
                                            <Eye size={12} />
                                            Inspect Proof ({tech.evidence.length})
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 3: Dependencies */}
                {activeTab === "Dependencies" && (
                    <div className="space-y-6">
                        {/* Runtime Dependencies */}
                        <div className="space-y-3">
                            <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                                Runtime Dependencies ({result.dependencies.runtime.length})
                            </h3>
                            {result.dependencies.runtime.length === 0 ? (
                                <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                    No runtime dependencies declared.
                                </p>
                            ) : (
                                <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
                                    {result.dependencies.runtime.map((d, i) => (
                                        <div
                                            key={`${d.name}-${i}`}
                                            className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-2.5"
                                        >
                                            <span className="font-mono text-xs font-semibold text-[color:var(--foreground)] truncate max-w-[160px]">
                                                {d.name}
                                            </span>
                                            <span className="rounded-md bg-[var(--accent)] px-1.5 py-0.5 font-mono text-[10px] text-[color:var(--muted-foreground)]">
                                                {d.version || "latest"}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>

                        {/* Dev Dependencies */}
                        <div className="space-y-3 pt-2">
                            <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                                Development Dependencies ({result.dependencies.development.length})
                            </h3>
                            {result.dependencies.development.length === 0 ? (
                                <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                    No development dependencies declared.
                                </p>
                            ) : (
                                <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
                                    {result.dependencies.development.map((d, i) => (
                                        <div
                                            key={`${d.name}-${i}`}
                                            className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-2.5"
                                        >
                                            <span className="font-mono text-xs font-semibold text-[color:var(--foreground)] truncate max-w-[160px]">
                                                {d.name}
                                            </span>
                                            <span className="rounded-md bg-[var(--accent)] px-1.5 py-0.5 font-mono text-[10px] text-[color:var(--muted-foreground)]">
                                                {d.version || "latest"}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>
                )}

                {/* Tab Content 4: Setup & Run Guide */}
                {activeTab === "Setup & Run Guide" && (
                    <div className="space-y-6">
                        {/* Prerequisites */}
                        {result.setup.prerequisites.length > 0 && (
                            <div className="space-y-2">
                                <h3 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Prerequisites
                                </h3>
                                <ul className="list-disc pl-5 text-xs text-[color:var(--foreground)] space-y-1">
                                    {result.setup.prerequisites.map((p, i) => (
                                        <li key={i}>{p}</li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {/* Install Commands */}
                        {result.setup.installCommands.length > 0 && (
                            <div className="space-y-2">
                                <h3 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Installation Commands
                                </h3>
                                {result.setup.installCommands.map((c, i) => (
                                    <div
                                        key={i}
                                        className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-3 font-mono text-xs"
                                    >
                                        <span className="text-[color:var(--foreground)]">{c.cmd}</span>
                                        <button
                                            type="button"
                                            onClick={() => copyText(c.cmd, `install-${i}`)}
                                            className="text-[color:var(--muted-foreground)] hover:text-[var(--primary)]"
                                        >
                                            {copiedIndex === `install-${i}` ? <Check size={14} /> : <Copy size={14} />}
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}

                        {/* Run Commands */}
                        {result.setup.runCommands.length > 0 && (
                            <div className="space-y-2">
                                <h3 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Execution Commands
                                </h3>
                                {result.setup.runCommands.map((c, i) => (
                                    <div
                                        key={i}
                                        className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-3 font-mono text-xs"
                                    >
                                        <span className="text-[color:var(--foreground)]">{c.cmd}</span>
                                        <button
                                            type="button"
                                            onClick={() => copyText(c.cmd, `run-${i}`)}
                                            className="text-[color:var(--muted-foreground)] hover:text-[var(--primary)]"
                                        >
                                            {copiedIndex === `run-${i}` ? <Check size={14} /> : <Copy size={14} />}
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 5: Environment Configuration */}
                {activeTab === "Environment Configuration" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Inferred Environment Variables ({result.environment.variables.length})
                        </h3>

                        {result.environment.variables.length === 0 ? (
                            <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                No environment variables detected in .env.example or source references.
                            </p>
                        ) : (
                            <div className="overflow-x-auto rounded-2xl border border-[color:var(--border)]">
                                <table className="w-full text-left text-xs">
                                    <thead className="bg-[var(--accent)] text-[color:var(--muted-foreground)] font-semibold border-b border-[color:var(--border)]">
                                        <tr>
                                            <th className="p-3">Variable</th>
                                            <th className="p-3">Inferred Type</th>
                                            <th className="p-3">Required</th>
                                            <th className="p-3">Source</th>
                                            <th className="p-3">Value</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-[color:var(--border)]">
                                        {result.environment.variables.map((v, i) => (
                                            <tr key={i} className="hover:bg-[var(--accent)]/50">
                                                <td className="p-3 font-mono font-bold text-[color:var(--foreground)]">
                                                    {v.name}
                                                </td>
                                                <td className="p-3">
                                                    <span className="rounded-md bg-[var(--primary)]/10 px-2 py-0.5 text-[10px] font-semibold text-[var(--primary)]">
                                                        {v.inferredType}
                                                    </span>
                                                </td>
                                                <td className="p-3 text-[color:var(--muted-foreground)]">
                                                    {v.required ? "Yes" : "No"}
                                                </td>
                                                <td className="p-3 font-mono text-[11px] text-[color:var(--muted-foreground)]">
                                                    {v.source}
                                                </td>
                                                <td className="p-3 font-mono text-[10px] text-amber-500">
                                                    •••••••• (Masked)
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 6: API Overview */}
                {activeTab === "API Overview" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Detected API Endpoints & Routes ({result.routes.length})
                        </h3>

                        {result.routes.length === 0 ? (
                            <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                No static REST or RPC endpoints detected.
                            </p>
                        ) : (
                            <div className="overflow-x-auto rounded-2xl border border-[color:var(--border)]">
                                <table className="w-full text-left text-xs">
                                    <thead className="bg-[var(--accent)] text-[color:var(--muted-foreground)] font-semibold border-b border-[color:var(--border)]">
                                        <tr>
                                            <th className="p-3">Method</th>
                                            <th className="p-3">Endpoint Path</th>
                                            <th className="p-3">Source File</th>
                                            <th className="p-3">Handler</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-[color:var(--border)]">
                                        {result.routes.map((r, i) => (
                                            <tr key={i} className="hover:bg-[var(--accent)]/50">
                                                <td className="p-3">
                                                    <span
                                                        className={`rounded-md px-2 py-0.5 font-mono text-[10px] font-bold ${
                                                            r.method === "GET"
                                                                ? "bg-blue-500/10 text-blue-500"
                                                                : r.method === "POST"
                                                                ? "bg-emerald-500/10 text-emerald-500"
                                                                : r.method === "DELETE"
                                                                ? "bg-red-500/10 text-red-500"
                                                                : "bg-amber-500/10 text-amber-500"
                                                        }`}
                                                    >
                                                        {r.method}
                                                    </span>
                                                </td>
                                                <td className="p-3 font-mono font-bold text-[color:var(--foreground)]">
                                                    {r.path}
                                                </td>
                                                <td className="p-3 font-mono text-[11px] text-[color:var(--muted-foreground)]">
                                                    {r.sourceFile}
                                                    {r.lineNumber ? `:${r.lineNumber}` : ""}
                                                </td>
                                                <td className="p-3 font-mono text-[11px] text-[color:var(--muted-foreground)]">
                                                    {r.inferredHandler || "inline"}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 7: Testing */}
                {activeTab === "Testing" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Testing Frameworks & Test Commands
                        </h3>

                        <div className="rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-3">
                            <div>
                                <p className="text-xs font-semibold text-[color:var(--muted-foreground)]">
                                    Detected Test Frameworks:
                                </p>
                                <div className="flex flex-wrap gap-2 pt-1">
                                    {result.testing.frameworks.length === 0 ? (
                                        <span className="text-xs text-[color:var(--muted-foreground)] italic">None detected</span>
                                    ) : (
                                        result.testing.frameworks.map((f, i) => (
                                            <span
                                                key={i}
                                                className="rounded-lg bg-[var(--primary)]/10 px-2.5 py-1 text-xs font-bold text-[var(--primary)]"
                                            >
                                                {f}
                                            </span>
                                        ))
                                    )}
                                </div>
                            </div>

                            {result.testing.testCommands.length > 0 && (
                                <div className="pt-2">
                                    <p className="text-xs font-semibold text-[color:var(--muted-foreground)]">
                                        Test Commands:
                                    </p>
                                    <div className="space-y-2 pt-1">
                                        {result.testing.testCommands.map((cmd, i) => (
                                            <div
                                                key={i}
                                                className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--card)] p-2.5 font-mono text-xs"
                                            >
                                                <span>{cmd}</span>
                                                <button
                                                    type="button"
                                                    onClick={() => copyText(cmd, `test-${i}`)}
                                                    className="text-[color:var(--muted-foreground)] hover:text-[var(--primary)]"
                                                >
                                                    {copiedIndex === `test-${i}` ? <Check size={14} /> : <Copy size={14} />}
                                                </button>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                )}

                {/* Tab Content 8: Deployment */}
                {activeTab === "Deployment" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Containerization & CI/CD Pipelines
                        </h3>

                        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                            <div className="rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-2">
                                <p className="text-xs font-bold text-[color:var(--foreground)]">
                                    Docker Available
                                </p>
                                <p className="text-lg font-extrabold text-[var(--primary)]">
                                    {result.deployment.dockerAvailable ? "Yes" : "No"}
                                </p>
                                {result.deployment.dockerfilePaths.length > 0 && (
                                    <p className="text-[11px] font-mono text-[color:var(--muted-foreground)]">
                                        {result.deployment.dockerfilePaths.join(", ")}
                                    </p>
                                )}
                            </div>

                            <div className="rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-2">
                                <p className="text-xs font-bold text-[color:var(--foreground)]">
                                    CI/CD Workflows
                                </p>
                                <p className="text-lg font-extrabold text-[var(--primary)]">
                                    {result.deployment.ciWorkflows.length} Workflows
                                </p>
                                {result.deployment.ciWorkflows.length > 0 && (
                                    <ul className="text-[11px] font-mono text-[color:var(--muted-foreground)] space-y-0.5">
                                        {result.deployment.ciWorkflows.map((w, i) => (
                                            <li key={i}>{w.name || w.path}</li>
                                        ))}
                                    </ul>
                                )}
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Evidence Inspector Modal */}
            {evidenceModalTech && (
                <EvidenceExplorer
                    isOpen={!!evidenceModalTech}
                    onClose={closeEvidenceModal}
                    title={evidenceModalTech.name}
                    evidenceList={evidenceModalTech.evidence.map((ev, i) => ({
                        id: `tech-ev-${i}`,
                        sourceType: "technology",
                        filePath: ev.filePath,
                        lineStart: ev.lineNumber,
                        lineEnd: ev.lineNumber,
                        symbol: null,
                        detector: ev.ruleType,
                        confidence: evidenceModalTech.confidence === "confirmed" ? "CONFIRMED" : "STRONGLY_INFERRED",
                        description: ev.detail
                    })) as unknown as Evidence[]}
                    negativeAssertions={evidenceModalTech.negativeAssertionsPassed}
                />
            )}
        </div>
    );
}
