"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import {
    ArrowLeft,
    Download,
    Check,
    Copy,
    FolderTree,
    Cpu,
    Boxes,
    Terminal,
    KeyRound,
    Network,
    TestTube2,
    Rocket,
    GitBranch,
    Eye,
    Clock,
    CheckCircle2,
} from "lucide-react";
import { useSharedTool } from "@/app/(site)/[toolId]/ClientToolLayout";
import {
    useRepositoryAnalyzer,
    ALL_REPORTS,
} from "@/context/RepositoryAnalyzerContext";
import RepositoryMapExplorer from "./explorers/RepositoryMapExplorer";
import ArchitectureExplorer from "./explorers/ArchitectureExplorer";
import EvidenceExplorer from "./explorers/EvidenceExplorer";
import RepositoryAnalyzerArchitectureSummary from "./RepositoryAnalyzerArchitectureSummary";
import { Evidence } from "@/types/analyzer";

export default function RepositoryAnalyzerDownload() {
    const router = useRouter();
    const { toolId, setFile } = useSharedTool();
    const {
        source,
        result,
        enableAi,
        evidenceModalTech,
        openEvidenceModal,
        closeEvidenceModal,
        reset,
    } = useRepositoryAnalyzer();

    const [activeTab, setActiveTab] = useState<string>("Project Structure");
    const [copiedIndex, setCopiedIndex] = useState<string | null>(null);

    // Empty state guard if accessed directly without result
    if (!result || !source) {
        return (
            <div className="mx-auto max-w-lg px-4 py-16 text-center">
                <div className="mx-auto inline-flex h-16 w-16 items-center justify-center rounded-3xl bg-[var(--primary)]/10 text-[var(--primary)]">
                    <GitBranch size={32} />
                </div>
                <h3 className="mt-6 text-xl font-bold text-[color:var(--foreground)]">
                    No analysis results available
                </h3>
                <p className="mt-2 text-sm text-[color:var(--muted-foreground)]">
                    Please select a project repository and run the analysis first.
                </p>
                <button
                    type="button"
                    onClick={() => {
                        setFile(null);
                        reset();
                        router.push(`/${toolId}`);
                    }}
                    className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-6 py-3 text-sm font-semibold text-white shadow-md transition hover:brightness-105"
                >
                    <ArrowLeft size={16} />
                    Start Analysis
                </button>
            </div>
        );
    }

    const reportIcons: Record<string, React.ReactNode> = {
        "Project Structure": <FolderTree size={18} className="text-blue-500" />,
        "Technology Stack": <Cpu size={18} className="text-indigo-500" />,
        "Dependencies": <Boxes size={18} className="text-emerald-500" />,
        "Setup & Run Guide": <Terminal size={18} className="text-amber-500" />,
        "Environment Configuration": <KeyRound size={18} className="text-purple-500" />,
        "API Overview": <Network size={18} className="text-cyan-500" />,
        "Testing": <TestTube2 size={18} className="text-rose-500" />,
        "Deployment": <Rocket size={18} className="text-orange-500" />,
    };

    const copyText = (text: string, id: string) => {
        navigator.clipboard.writeText(text);
        setCopiedIndex(id);
        setTimeout(() => setCopiedIndex(null), 2000);
    };

    // Generate comprehensive Markdown from canonical result
    const generateMarkdown = (): string => {
        let md = `# Architecture Analysis Report: ${result.repository.name}\n\n`;
        md += `> Generated by PDFNest Repository Analyzer (Engine: ${result.provenance.engine} v${result.provenance.engineVersion})\n\n`;
        md += `**Execution Time:** ${result.provenance.durationMs} ms | **Complexity Tier:** ${result.provenance.complexityTier} | **Total Files:** ${result.metrics.totalFiles}\n\n`;

        // 0. AI Architecture Synthesis (if present)
        const aiSummary = result.ai || result.architectureSummary;
        if (aiSummary && aiSummary.summary) {
            md += `## AI Architecture Synthesis\n\n`;
            md += `> **Synthesis Engine:** ${aiSummary.provider || "Gemini"} (${aiSummary.model || "gemini-2.5-flash"}) | **Fact-Grounded Single-Shot Synthesis**\n\n`;
            md += `### Executive Summary\n\n${aiSummary.summary}\n\n`;
            if (aiSummary.architecturePattern) {
                md += `### Architecture Pattern\n\n- **Pattern:** \`${aiSummary.architecturePattern}\`\n\n`;
            }
            if (aiSummary.keyComponents && aiSummary.keyComponents.length > 0) {
                md += `### Key Architectural Components\n\n`;
                aiSummary.keyComponents.forEach((comp) => {
                    md += `- **${comp.name}**: ${comp.role}`;
                    if (comp.factIds && comp.factIds.length > 0) {
                        md += ` *(Facts: \`${comp.factIds.join("`, `")}\`)*`;
                    }
                    md += `\n`;
                });
                md += `\n`;
            }
            if (aiSummary.dataFlow && aiSummary.dataFlow.length > 0) {
                md += `### Data & Execution Flow\n\n`;
                aiSummary.dataFlow.forEach((step, idx) => {
                    md += `${step.step || idx + 1}. ${step.description}`;
                    if (step.factIds && step.factIds.length > 0) {
                        md += ` *(Facts: \`${step.factIds.join("`, `")}\`)*`;
                    }
                    md += `\n`;
                });
                md += `\n`;
            }
            if (aiSummary.risks && aiSummary.risks.length > 0) {
                md += `### Architectural Considerations & Risks\n\n`;
                aiSummary.risks.forEach((risk) => {
                    md += `- **[${risk.category}]**: ${risk.description}`;
                    if (risk.factIds && risk.factIds.length > 0) {
                        md += ` *(Facts: \`${risk.factIds.join("`, `")}\`)*`;
                    }
                    md += `\n`;
                });
                md += `\n`;
            }
        } else {
            md += `## AI Architecture Synthesis\n\n*AI architecture synthesis was not requested or was unavailable. All findings below are 100% deterministically verified from repository code, ASTs, and package manifests.*\n\n`;
        }

        // 1. Structure
        md += `## 1. Project Structure\n\n\`\`\`text\n${result.structureTree}\n\`\`\`\n\n`;

        // 2. Tech Stack
        md += `## 2. Verified Technology Stack\n\n`;
        result.technologies.forEach((t) => {
            md += `- **${t.name}** (${t.category}, ${t.confidence})`;
            if (t.version) md += ` - Version: \`${t.version}\``;
            md += `\n`;
            if (t.negativeAssertionsPassed && t.negativeAssertionsPassed.length > 0) {
                md += `  - Negative Assertions Passed: ${t.negativeAssertionsPassed.join(", ")}\n`;
            }
        });
        md += `\n`;

        // 3. Dependencies
        md += `## 3. Dependencies\n\n### Runtime Dependencies\n`;
        result.dependencies.runtime.forEach((d) => {
            md += `- \`${d.name}\` (${d.version}) [${d.manager}]\n`;
        });
        md += `\n### Development Dependencies\n`;
        result.dependencies.development.forEach((d) => {
            md += `- \`${d.name}\` (${d.version}) [${d.manager}]\n`;
        });
        md += `\n`;

        // 4. Setup
        md += `## 4. Setup & Run Guide\n\n`;
        if (result.setup.installCommands.length > 0) {
            md += `### Installation\n\`\`\`bash\n${result.setup.installCommands.map((c) => c.cmd).join("\n")}\n\`\`\`\n\n`;
        }
        if (result.setup.runCommands.length > 0) {
            md += `### Running\n\`\`\`bash\n${result.setup.runCommands.map((c) => c.cmd).join("\n")}\n\`\`\`\n\n`;
        }

        // 5. Environment
        md += `## 5. Environment Configuration\n\n| Variable | Inferred Type | Required | Source |\n|---|---|---|---|\n`;
        result.environment.variables.forEach((v) => {
            md += `| \`${v.name}\` | \`${v.inferredType}\` | ${v.required ? "Yes" : "No"} | \`${v.source}\` |\n`;
        });
        md += `\n`;

        // 6. Routes
        md += `## 6. API Routes\n\n| Method | Path | Handler | Auth Required |\n|---|---|---|---|\n`;
        result.routes.forEach((r) => {
            md += `| **${r.method}** | \`${r.path}\` | \`${r.inferredHandler || "inline"}\` | ${r.authRequired ? "Yes" : "No"} |\n`;
        });
        md += `\n`;

        // 7. Testing
        md += `## 7. Testing\n\n`;
        md += `- **Frameworks:** ${result.testing.frameworks.join(", ") || "None detected"}\n`;
        if (result.testing.testCommands.length > 0) {
            md += `\`\`\`bash\n${result.testing.testCommands.join("\n")}\n\`\`\`\n\n`;
        }

        // 8. Deployment
        md += `## 8. Deployment & CI/CD\n\n`;
        md += `- **Docker Available:** ${result.deployment.dockerAvailable ? "Yes" : "No"}\n`;
        if (result.deployment.dockerfilePaths.length > 0) {
            md += `- **Dockerfiles:** \`${result.deployment.dockerfilePaths.join("`, `")}\`\n`;
        }

        return md;
    };

    const downloadMarkdown = () => {
        const md = generateMarkdown();
        const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${result.repository.name}-architecture-report.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    };

    return (
        <div className="mx-auto max-w-5xl space-y-8 px-4 py-6">
            {/* Step Progress Bar */}
            <div className="flex items-center justify-center">
                <nav aria-label="Progress" className="flex items-center gap-2 rounded-full border border-[color:var(--border)] bg-[var(--card)] px-4 py-1.5 text-xs font-semibold">
                    <span className="text-[color:var(--muted-foreground)]">1 Source</span>
                    <span className="text-[color:var(--border)]">/</span>
                    <span className="text-[color:var(--muted-foreground)]">2 Scoping</span>
                    <span className="text-[color:var(--border)]">/</span>
                    <span className="flex items-center gap-1 text-[var(--primary)] font-bold">
                        <span className="flex h-4 w-4 items-center justify-center rounded-full bg-[var(--primary)] text-[10px] text-white">3</span>
                        Documentation
                    </span>
                </nav>
            </div>

            {/* Header & Provenance Card */}
            <div className="rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm space-y-4">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex items-center gap-4">
                        <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-500">
                            <CheckCircle2 size={24} />
                        </div>
                        <div>
                            <div className="flex items-center gap-2">
                                <h1 className="text-xl font-bold text-[color:var(--foreground)] sm:text-2xl">
                                    {result.repository.name}
                                </h1>
                                <span className="rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
                                    Analysis Complete
                                </span>
                            </div>
                            <p className="mt-1 text-xs text-[color:var(--muted-foreground)] flex items-center gap-2">
                                <span>Tier: {result.provenance.complexityTier}</span>
                                <span>•</span>
                                <span className="flex items-center gap-1">
                                    <Clock size={12} />
                                    {result.provenance.durationMs}ms
                                </span>
                                <span>•</span>
                                <span>{result.metrics.totalFiles} files</span>
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-3">
                        <button
                            type="button"
                            onClick={downloadMarkdown}
                            className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-xs font-semibold text-white shadow-sm transition hover:brightness-105"
                        >
                            <Download size={14} />
                            Export Markdown
                        </button>
                        <button
                            type="button"
                            onClick={() => {
                                setFile(null);
                                reset();
                                router.push(`/${toolId}`);
                            }}
                            className="inline-flex items-center gap-1.5 rounded-xl border border-[color:var(--border)] bg-[var(--background)] px-3.5 py-2.5 text-xs font-semibold text-[color:var(--muted-foreground)] hover:bg-[var(--accent)] hover:text-[color:var(--foreground)]"
                        >
                            <ArrowLeft size={14} />
                            New Analysis
                        </button>
                    </div>
                </div>
            </div>

            {/* AI Architecture Synthesis */}
            <RepositoryAnalyzerArchitectureSummary
                summary={result.ai || result.architectureSummary}
                aiRequested={enableAi}
            />

            {/* 8 Documentation Domain Tabs */}
            <div className="rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm space-y-6">
                {/* Tab Navigation */}
                <div className="flex overflow-x-auto border-b border-[color:var(--border)] pb-3 gap-2">
                    {ALL_REPORTS.map((r) => {
                        const isActive = activeTab === r.id;
                        return (
                            <button
                                key={r.id}
                                type="button"
                                onClick={() => setActiveTab(r.id)}
                                className={`inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-xs font-semibold whitespace-nowrap transition ${
                                    isActive
                                        ? "bg-[var(--primary)] text-white shadow-xs"
                                        : "text-[color:var(--muted-foreground)] hover:bg-[var(--accent)] hover:text-[color:var(--foreground)]"
                                }`}
                            >
                                {reportIcons[r.id]}
                                {r.title}
                            </button>
                        );
                    })}
                </div>

                {/* Tab Content 1: Project Structure */}
                {activeTab === "Project Structure" && (
                    <div className="space-y-6">
                        <div className="flex items-center justify-between">
                            <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                                Directory Hierarchy & Filesystem Layout
                            </h3>
                            <button
                                type="button"
                                onClick={() => copyText(result.structureTree, "tree")}
                                className="inline-flex items-center gap-1 text-xs font-semibold text-[var(--primary)] hover:underline"
                            >
                                {copiedIndex === "tree" ? <Check size={14} /> : <Copy size={14} />}
                                {copiedIndex === "tree" ? "Copied" : "Copy Tree"}
                            </button>
                        </div>

                        <div className="h-[500px]">
                            <RepositoryMapExplorer result={result} />
                        </div>

                        {/* Language Distribution Breakdown */}
                        {result.metrics.languages.length > 0 && (
                            <div className="space-y-3 pt-2">
                                <h4 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Language Distribution
                                </h4>
                                <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                                    {result.metrics.languages.map((l) => (
                                        <div
                                            key={l.name}
                                            className="rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-3 text-center"
                                        >
                                            <p className="text-xs font-bold text-[color:var(--foreground)]">{l.name}</p>
                                            <p className="mt-1 text-lg font-extrabold text-[var(--primary)]">
                                                {l.percentage.toFixed(1)}%
                                            </p>
                                            <p className="text-[10px] text-[color:var(--muted-foreground)]">
                                                {l.fileCount} files ({Math.round(l.bytes / 1024)} KB)
                                            </p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 2: Technology Stack */}
                {activeTab === "Technology Stack" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Evidence-Based Technology Detection ({result.technologies.length})
                        </h3>

                        {result.technologies.length === 0 ? (
                            <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                No specific technologies or frameworks detected.
                            </p>
                        ) : (
                            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
                                {result.technologies.map((tech) => (
                                    <div
                                        key={tech.id}
                                        className="flex flex-col justify-between rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-3"
                                    >
                                        <div>
                                            <div className="flex items-center justify-between">
                                                <h4 className="text-sm font-bold text-[color:var(--foreground)]">
                                                    {tech.name}
                                                </h4>
                                                <span className="rounded-full bg-[var(--primary)]/10 px-2 py-0.5 text-[10px] font-bold text-[var(--primary)] uppercase">
                                                    {tech.confidence}
                                                </span>
                                            </div>
                                            <p className="text-[11px] text-[color:var(--muted-foreground)] capitalize mt-0.5">
                                                {tech.category} {tech.version ? `• v${tech.version}` : ""}
                                            </p>
                                        </div>

                                        {tech.negativeAssertionsPassed && tech.negativeAssertionsPassed.length > 0 && (
                                            <div className="text-[10px] text-emerald-600 dark:text-emerald-400">
                                                ✓ Negated: {tech.negativeAssertionsPassed.join(", ")}
                                            </div>
                                        )}

                                        <button
                                            type="button"
                                            onClick={() => openEvidenceModal(tech)}
                                            className="inline-flex items-center justify-center gap-1 rounded-xl border border-[color:var(--border)] bg-[var(--card)] py-1.5 text-xs font-semibold text-[color:var(--foreground)] hover:bg-[var(--accent)]"
                                        >
                                            <Eye size={12} />
                                            Inspect Proof ({tech.evidence.length})
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 3: Dependencies */}
                {activeTab === "Dependencies" && (
                    <div className="space-y-6">
                        {/* Runtime Dependencies */}
                        <div className="space-y-3">
                            <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                                Runtime Dependencies ({result.dependencies.runtime.length})
                            </h3>
                            {result.dependencies.runtime.length === 0 ? (
                                <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                    No runtime dependencies declared.
                                </p>
                            ) : (
                                <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
                                    {result.dependencies.runtime.map((d, i) => (
                                        <div
                                            key={`${d.name}-${i}`}
                                            className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-2.5"
                                        >
                                            <span className="font-mono text-xs font-semibold text-[color:var(--foreground)] truncate max-w-[160px]">
                                                {d.name}
                                            </span>
                                            <span className="rounded-md bg-[var(--accent)] px-1.5 py-0.5 font-mono text-[10px] text-[color:var(--muted-foreground)]">
                                                {d.version || "latest"}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>

                        {/* Dev Dependencies */}
                        <div className="space-y-3 pt-2">
                            <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                                Development Dependencies ({result.dependencies.development.length})
                            </h3>
                            {result.dependencies.development.length === 0 ? (
                                <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                    No development dependencies declared.
                                </p>
                            ) : (
                                <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
                                    {result.dependencies.development.map((d, i) => (
                                        <div
                                            key={`${d.name}-${i}`}
                                            className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-2.5"
                                        >
                                            <span className="font-mono text-xs font-semibold text-[color:var(--foreground)] truncate max-w-[160px]">
                                                {d.name}
                                            </span>
                                            <span className="rounded-md bg-[var(--accent)] px-1.5 py-0.5 font-mono text-[10px] text-[color:var(--muted-foreground)]">
                                                {d.version || "latest"}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>
                )}

                {/* Tab Content 4: Setup & Run Guide */}
                {activeTab === "Setup & Run Guide" && (
                    <div className="space-y-6">
                        {/* Prerequisites */}
                        {result.setup.prerequisites.length > 0 && (
                            <div className="space-y-2">
                                <h3 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Prerequisites
                                </h3>
                                <ul className="list-disc pl-5 text-xs text-[color:var(--foreground)] space-y-1">
                                    {result.setup.prerequisites.map((p, i) => (
                                        <li key={i}>{p}</li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {/* Install Commands */}
                        {result.setup.installCommands.length > 0 && (
                            <div className="space-y-2">
                                <h3 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Installation Commands
                                </h3>
                                {result.setup.installCommands.map((c, i) => (
                                    <div
                                        key={i}
                                        className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-3 font-mono text-xs"
                                    >
                                        <span className="text-[color:var(--foreground)]">{c.cmd}</span>
                                        <button
                                            type="button"
                                            onClick={() => copyText(c.cmd, `install-${i}`)}
                                            className="text-[color:var(--muted-foreground)] hover:text-[var(--primary)]"
                                        >
                                            {copiedIndex === `install-${i}` ? <Check size={14} /> : <Copy size={14} />}
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}

                        {/* Run Commands */}
                        {result.setup.runCommands.length > 0 && (
                            <div className="space-y-2">
                                <h3 className="text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                                    Execution Commands
                                </h3>
                                {result.setup.runCommands.map((c, i) => (
                                    <div
                                        key={i}
                                        className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--background)] p-3 font-mono text-xs"
                                    >
                                        <span className="text-[color:var(--foreground)]">{c.cmd}</span>
                                        <button
                                            type="button"
                                            onClick={() => copyText(c.cmd, `run-${i}`)}
                                            className="text-[color:var(--muted-foreground)] hover:text-[var(--primary)]"
                                        >
                                            {copiedIndex === `run-${i}` ? <Check size={14} /> : <Copy size={14} />}
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 5: Environment Configuration */}
                {activeTab === "Environment Configuration" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Inferred Environment Variables ({result.environment.variables.length})
                        </h3>

                        {result.environment.variables.length === 0 ? (
                            <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                No environment variables detected in .env.example or source references.
                            </p>
                        ) : (
                            <div className="overflow-x-auto rounded-2xl border border-[color:var(--border)]">
                                <table className="w-full text-left text-xs">
                                    <thead className="bg-[var(--accent)] text-[color:var(--muted-foreground)] font-semibold border-b border-[color:var(--border)]">
                                        <tr>
                                            <th className="p-3">Variable</th>
                                            <th className="p-3">Inferred Type</th>
                                            <th className="p-3">Required</th>
                                            <th className="p-3">Source</th>
                                            <th className="p-3">Value</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-[color:var(--border)]">
                                        {result.environment.variables.map((v, i) => (
                                            <tr key={i} className="hover:bg-[var(--accent)]/50">
                                                <td className="p-3 font-mono font-bold text-[color:var(--foreground)]">
                                                    {v.name}
                                                </td>
                                                <td className="p-3">
                                                    <span className="rounded-md bg-[var(--primary)]/10 px-2 py-0.5 text-[10px] font-semibold text-[var(--primary)]">
                                                        {v.inferredType}
                                                    </span>
                                                </td>
                                                <td className="p-3 text-[color:var(--muted-foreground)]">
                                                    {v.required ? "Yes" : "No"}
                                                </td>
                                                <td className="p-3 font-mono text-[11px] text-[color:var(--muted-foreground)]">
                                                    {v.source}
                                                </td>
                                                <td className="p-3 font-mono text-[10px] text-amber-500">
                                                    •••••••• (Masked)
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 6: API Overview */}
                {activeTab === "API Overview" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Detected API Endpoints & Routes ({result.routes.length})
                        </h3>

                        {result.routes.length === 0 ? (
                            <p className="text-xs text-[color:var(--muted-foreground)] italic">
                                No static REST or RPC endpoints detected.
                            </p>
                        ) : (
                            <div className="overflow-x-auto rounded-2xl border border-[color:var(--border)]">
                                <table className="w-full text-left text-xs">
                                    <thead className="bg-[var(--accent)] text-[color:var(--muted-foreground)] font-semibold border-b border-[color:var(--border)]">
                                        <tr>
                                            <th className="p-3">Method</th>
                                            <th className="p-3">Endpoint Path</th>
                                            <th className="p-3">Source File</th>
                                            <th className="p-3">Handler</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-[color:var(--border)]">
                                        {result.routes.map((r, i) => (
                                            <tr key={i} className="hover:bg-[var(--accent)]/50">
                                                <td className="p-3">
                                                    <span
                                                        className={`rounded-md px-2 py-0.5 font-mono text-[10px] font-bold ${
                                                            r.method === "GET"
                                                                ? "bg-blue-500/10 text-blue-500"
                                                                : r.method === "POST"
                                                                ? "bg-emerald-500/10 text-emerald-500"
                                                                : r.method === "DELETE"
                                                                ? "bg-red-500/10 text-red-500"
                                                                : "bg-amber-500/10 text-amber-500"
                                                        }`}
                                                    >
                                                        {r.method}
                                                    </span>
                                                </td>
                                                <td className="p-3 font-mono font-bold text-[color:var(--foreground)]">
                                                    {r.path}
                                                </td>
                                                <td className="p-3 font-mono text-[11px] text-[color:var(--muted-foreground)]">
                                                    {r.sourceFile}
                                                    {r.lineNumber ? `:${r.lineNumber}` : ""}
                                                </td>
                                                <td className="p-3 font-mono text-[11px] text-[color:var(--muted-foreground)]">
                                                    {r.inferredHandler || "inline"}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </div>
                )}

                {/* Tab Content 7: Testing */}
                {activeTab === "Testing" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Testing Frameworks & Test Commands
                        </h3>

                        <div className="rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-3">
                            <div>
                                <p className="text-xs font-semibold text-[color:var(--muted-foreground)]">
                                    Detected Test Frameworks:
                                </p>
                                <div className="flex flex-wrap gap-2 pt-1">
                                    {result.testing.frameworks.length === 0 ? (
                                        <span className="text-xs text-[color:var(--muted-foreground)] italic">None detected</span>
                                    ) : (
                                        result.testing.frameworks.map((f, i) => (
                                            <span
                                                key={i}
                                                className="rounded-lg bg-[var(--primary)]/10 px-2.5 py-1 text-xs font-bold text-[var(--primary)]"
                                            >
                                                {f}
                                            </span>
                                        ))
                                    )}
                                </div>
                            </div>

                            {result.testing.testCommands.length > 0 && (
                                <div className="pt-2">
                                    <p className="text-xs font-semibold text-[color:var(--muted-foreground)]">
                                        Test Commands:
                                    </p>
                                    <div className="space-y-2 pt-1">
                                        {result.testing.testCommands.map((cmd, i) => (
                                            <div
                                                key={i}
                                                className="flex items-center justify-between rounded-xl border border-[color:var(--border)] bg-[var(--card)] p-2.5 font-mono text-xs"
                                            >
                                                <span>{cmd}</span>
                                                <button
                                                    type="button"
                                                    onClick={() => copyText(cmd, `test-${i}`)}
                                                    className="text-[color:var(--muted-foreground)] hover:text-[var(--primary)]"
                                                >
                                                    {copiedIndex === `test-${i}` ? <Check size={14} /> : <Copy size={14} />}
                                                </button>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                )}

                {/* Tab Content 8: Deployment */}
                {activeTab === "Deployment" && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-[color:var(--foreground)]">
                            Containerization & CI/CD Pipelines
                        </h3>

                        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                            <div className="rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-2">
                                <p className="text-xs font-bold text-[color:var(--foreground)]">
                                    Docker Available
                                </p>
                                <p className="text-lg font-extrabold text-[var(--primary)]">
                                    {result.deployment.dockerAvailable ? "Yes" : "No"}
                                </p>
                                {result.deployment.dockerfilePaths.length > 0 && (
                                    <p className="text-[11px] font-mono text-[color:var(--muted-foreground)]">
                                        {result.deployment.dockerfilePaths.join(", ")}
                                    </p>
                                )}
                            </div>

                            <div className="rounded-2xl border border-[color:var(--border)] bg-[var(--background)] p-4 space-y-2">
                                <p className="text-xs font-bold text-[color:var(--foreground)]">
                                    CI/CD Workflows
                                </p>
                                <p className="text-lg font-extrabold text-[var(--primary)]">
                                    {result.deployment.ciWorkflows.length} Workflows
                                </p>
                                {result.deployment.ciWorkflows.length > 0 && (
                                    <ul className="text-[11px] font-mono text-[color:var(--muted-foreground)] space-y-0.5">
                                        {result.deployment.ciWorkflows.map((w, i) => (
                                            <li key={i}>{w.name || w.path}</li>
                                        ))}
                                    </ul>
                                )}
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Evidence Inspector Modal */}
            {evidenceModalTech && (
                <EvidenceExplorer
                    isOpen={!!evidenceModalTech}
                    onClose={closeEvidenceModal}
                    title={evidenceModalTech.name}
                    evidenceList={evidenceModalTech.evidence.map((ev, i) => ({
                        id: `tech-ev-${i}`,
                        sourceType: "technology",
                        filePath: ev.filePath,
                        lineStart: ev.lineNumber,
                        lineEnd: ev.lineNumber,
                        symbol: null,
                        detector: ev.ruleType,
                        confidence: evidenceModalTech.confidence === "confirmed" ? "CONFIRMED" : "STRONGLY_INFERRED",
                        description: ev.detail
                    })) as unknown as Evidence[]}
                    negativeAssertions={evidenceModalTech.negativeAssertionsPassed}
                />
            )}
        </div>
    );
}
