"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import {
    ShieldCheck,
    ArrowLeft,
    Download,
    FileText,
    FileCode,
    Check,
    Copy,
    FolderTree,
    Cpu,
    Boxes,
    Terminal,
    KeyRound,
    Network,
    TestTube2,
    Rocket,
    Sparkles,
    GitBranch,
    Info,
    ExternalLink,
} from "lucide-react";
import { useSharedTool } from "@/app/(site)/[toolId]/ClientToolLayout";
import {
    useRepositoryAnalyzer,
    ALL_REPORTS,
} from "@/context/RepositoryAnalyzerContext";

export default function RepositoryAnalyzerDownload() {
    const router = useRouter();
    const { toolId, setFile } = useSharedTool();
    const {
        source,
        selectedReports,
        mockProject,
        reset,
    } = useRepositoryAnalyzer();

    const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
    const [pdfNoticeVisible, setPdfNoticeVisible] = useState(false);

    // Empty state guard if accessed directly without source
    if (!source || selectedReports.length === 0) {
        return (
            <div className="mx-auto max-w-lg px-4 py-16 text-center">
                <div className="mx-auto inline-flex h-16 w-16 items-center justify-center rounded-3xl bg-[var(--primary)]/10 text-[var(--primary)]">
                    <GitBranch size={32} />
                </div>
                <h3 className="mt-6 text-xl font-bold text-[color:var(--foreground)]">
                    No generated documentation
                </h3>
                <p className="mt-2 text-sm text-[color:var(--muted-foreground)]">
                    Please select a project repository and generate documentation first.
                </p>
                <button
                    type="button"
                    onClick={() => {
                        setFile(null);
                        reset();
                        router.push(`/${toolId}`);
                    }}
                    className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-6 py-3 text-sm font-semibold text-white shadow-md transition hover:brightness-105"
                >
                    <ArrowLeft size={16} />
                    Start Analysis
                </button>
            </div>
        );
    }

    const reportIcons: Record<string, React.ReactNode> = {
        "Project Structure": <FolderTree size={20} className="text-blue-500" />,
        "Technology Stack": <Cpu size={20} className="text-indigo-500" />,
        "Dependencies": <Boxes size={20} className="text-emerald-500" />,
        "Setup & Run Guide": <Terminal size={20} className="text-amber-500" />,
        "Environment Configuration": <KeyRound size={20} className="text-purple-500" />,
        "API Overview": <Network size={20} className="text-cyan-500" />,
        "Testing": <TestTube2 size={20} className="text-rose-500" />,
        "Deployment": <Rocket size={20} className="text-orange-500" />,
    };

    const setupCommands = [
        { label: "Install Node dependencies", cmd: "npm install" },
        { label: "Start frontend dev server", cmd: "npm run dev" },
        { label: "Download Go modules", cmd: "go mod download" },
        { label: "Start backend server", cmd: "go run ./cmd/server" },
    ];

    const copyToClipboard = (text: string, index: number) => {
        navigator.clipboard.writeText(text);
        setCopiedIndex(index);
        setTimeout(() => setCopiedIndex(null), 2000);
    };

    const generateMarkdownContent = (reportTitle?: string): string => {
        const repoName = mockProject.name;
        let content = `# ${repoName}\n\n`;
        content += `> Generated by Platen Repository Analyzer (UI Analysis Simulation)\n\n`;

        const includeAll = !reportTitle;

        if (includeAll || reportTitle === "Project Structure") {
            content += `## Project Structure\n\n\`\`\`text\n${repoName}/\n├── app/\n│   ├── (site)/\n│   ├── api/\n│   └── layout.tsx\n├── components/\n├── context/\n├── lib/\n├── public/\n├── backend/\n├── package.json\n├── README.md\n└── docker-compose.yml\n\`\`\`\n\n`;
        }

        if (includeAll || reportTitle === "Technology Stack") {
            content += `## Technology Stack\n\n- **Languages**: ${mockProject.languages.join(", ")}\n- **Frameworks**: ${mockProject.frameworks.join(", ")}\n- **Database**: ${mockProject.database.join(", ")}\n- **Infrastructure**: ${mockProject.infrastructure.join(", ")}\n\n`;
        }

        if (includeAll || reportTitle === "Dependencies") {
            content += `## Dependencies\n\n### Production\n- next (^15.0.0)\n- react (^19.0.0)\n- react-dom (^19.0.0)\n- lucide-react (^0.454.0)\n\n### Development\n- typescript (^5.0.0)\n- tailwindcss (^3.4.0)\n- eslint (^9.0.0)\n\n`;
        }

        if (includeAll || reportTitle === "Setup & Run Guide") {
            content += `## Setup & Run Guide\n\n\`\`\`bash\n# Install frontend dependencies\nnpm install\n\n# Run frontend development server\nnpm run dev\n\n# Download Go modules (backend)\ngo mod download\n\n# Start backend service\ngo run ./cmd/server\n\`\`\`\n\n`;
        }

        if (includeAll || reportTitle === "Environment Configuration") {
            content += `## Environment Configuration\n\n\`\`\`env\nPORT=3000\nNODE_ENV=development\nNEXT_PUBLIC_APP_URL=http://localhost:3000\nDATABASE_URL=postgresql://user:password@localhost:5432/${repoName}\n\`\`\`\n\n`;
        }

        if (includeAll || reportTitle === "API Overview") {
            content += `## API Overview\n\n| Endpoint | Method | Description |\n|---|---|---|\n| \`/api/health\` | GET | Healthcheck and readiness probe |\n| \`/api/tools\` | GET | List available tool catalog entries |\n| \`/api/analyze\` | POST | Submit repository analysis request |\n\n`;
        }

        if (includeAll || reportTitle === "Testing") {
            content += `## Testing\n\n\`\`\`bash\n# Run unit and integration tests\nnpm test\n\n# Run Playwright E2E suites\nnpx playwright test\n\`\`\`\n\n`;
        }

        if (includeAll || reportTitle === "Deployment") {
            content += `## Deployment\n\n\`\`\`bash\n# Build container image\ndocker build -t ${repoName}:latest .\n\n# Run with Docker Compose\ndocker-compose up -d\n\`\`\`\n\n`;
        }

        return content;
    };

    const downloadMarkdown = (reportTitle?: string) => {
        const text = generateMarkdownContent(reportTitle);
        const fileName = reportTitle
            ? `${mockProject.name}-${reportTitle.toLowerCase().replace(/\s+/g, "-")}.md`
            : `${mockProject.name}-documentation.md`;

        const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
        const downloadUrl = window.URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = downloadUrl;
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(downloadUrl);
    };

    const handlePdfClick = () => {
        setPdfNoticeVisible(true);
        setTimeout(() => setPdfNoticeVisible(false), 3500);
    };

    const handleStartOver = () => {
        setFile(null);
        reset();
        router.push(`/${toolId}`);
    };

    const activeSections = ALL_REPORTS.filter((r) => selectedReports.includes(r.id));

    return (
        <div className="mx-auto max-w-5xl space-y-10 px-4 py-8">
            {/* PDF Notice Modal/Toast */}
            {pdfNoticeVisible && (
                <div className="fixed bottom-6 right-6 z-50 flex max-w-md items-center gap-3 rounded-2xl border border-indigo-500/30 bg-[var(--card)] p-4 shadow-xl ring-1 ring-indigo-500/20 backdrop-blur-md">
                    <Info size={20} className="shrink-0 text-indigo-500" />
                    <p className="text-xs text-[color:var(--foreground)]">
                        PDF export will be available when repository analysis is implemented.
                    </p>
                </div>
            )}

            {/* Header / Success Badge */}
            <div className="text-center space-y-3">
                <div className="mx-auto inline-flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-500/10 text-emerald-600">
                    <ShieldCheck size={36} />
                </div>

                <div className="inline-flex items-center gap-2 rounded-full border border-[color:var(--border)] bg-[var(--card)] px-3.5 py-1 text-xs font-semibold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                    <Sparkles size={13} className="text-[var(--primary)]" />
                    <span>Step 3 of 3</span>
                </div>

                <h1 className="text-3xl font-black tracking-tight text-[color:var(--foreground)] sm:text-4xl">
                    Documentation Ready
                </h1>

                <p className="mx-auto max-w-xl text-sm leading-relaxed text-[color:var(--muted-foreground)]">
                    Your repository documentation has been generated for{" "}
                    <span className="font-bold text-[color:var(--foreground)]">
                        {mockProject.name}
                    </span>
                    .
                </p>

                {/* Primary Actions */}
                <div className="flex flex-col items-center justify-center gap-4 pt-4 sm:flex-row">
                    <button
                        type="button"
                        onClick={() => downloadMarkdown()}
                        className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-8 py-4 font-bold text-white shadow-lg transition hover:brightness-105 sm:w-auto"
                    >
                        <Download size={18} />
                        Download All (Markdown)
                    </button>

                    <button
                        type="button"
                        onClick={handleStartOver}
                        className="flex w-full items-center justify-center gap-2 rounded-xl border border-[color:var(--border)] bg-[var(--card)] px-6 py-4 font-semibold text-[color:var(--foreground)] transition hover:bg-[color:var(--background)] sm:w-auto"
                    >
                        <ArrowLeft size={18} />
                        Start Over
                    </button>
                </div>
            </div>

            {/* Generated Reports Grid */}
            <div className="space-y-4">
                <h2 className="text-lg font-bold text-[color:var(--foreground)]">
                    Generated Report Sections ({activeSections.length})
                </h2>

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-2">
                    {activeSections.map((section) => (
                        <div
                            key={section.id}
                            className="flex flex-col justify-between rounded-2xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm"
                        >
                            <div className="flex items-start gap-4">
                                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[color:var(--background)] border border-[color:var(--border)]">
                                    {reportIcons[section.id] || <Sparkles size={20} />}
                                </div>
                                <div className="space-y-1">
                                    <h3 className="text-base font-bold text-[color:var(--foreground)]">
                                        {section.title}
                                    </h3>
                                    <p className="text-xs leading-relaxed text-[color:var(--muted-foreground)]">
                                        {section.description}
                                    </p>
                                </div>
                            </div>

                            <div className="mt-6 flex items-center gap-2 border-t border-[color:var(--border)] pt-4">
                                <button
                                    type="button"
                                    onClick={() => downloadMarkdown(section.title)}
                                    className="flex flex-1 items-center justify-center gap-1.5 rounded-xl border border-[color:var(--border)] bg-[color:var(--background)] py-2 text-xs font-semibold text-[color:var(--foreground)] transition hover:border-[var(--primary)] hover:text-[var(--primary)]"
                                >
                                    <FileCode size={14} />
                                    Markdown
                                </button>

                                <button
                                    type="button"
                                    onClick={handlePdfClick}
                                    className="flex flex-1 items-center justify-center gap-1.5 rounded-xl border border-[color:var(--border)] bg-[color:var(--background)] py-2 text-xs font-semibold text-[color:var(--muted-foreground)] transition hover:border-indigo-500/50 hover:text-[color:var(--foreground)]"
                                >
                                    <FileText size={14} />
                                    PDF
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Project Tree Preview */}
            <div className="space-y-3 rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm sm:p-8">
                <div className="flex items-center gap-3">
                    <FolderTree size={22} className="text-blue-500" />
                    <div>
                        <h2 className="text-base font-bold text-[color:var(--foreground)]">
                            Project Tree Preview
                        </h2>
                        <p className="text-xs text-[color:var(--muted-foreground)]">
                            Directory hierarchy generated for {mockProject.name}
                        </p>
                    </div>
                </div>

                <div className="rounded-2xl border border-[color:var(--border)] bg-[color:var(--background)] p-4 font-mono text-xs text-[color:var(--foreground)] overflow-x-auto leading-relaxed">
                    <pre>
{`platen/
├── app/
│   ├── (site)/
│   ├── api/
│   └── layout.tsx
├── components/
├── context/
├── lib/
├── public/
├── backend/
├── package.json
├── README.md
└── docker-compose.yml`}
                    </pre>
                </div>
            </div>

            {/* Setup Guide Preview with Copy Buttons */}
            <div className="space-y-4 rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-6 shadow-sm sm:p-8">
                <div className="flex items-center gap-3">
                    <Terminal size={22} className="text-amber-500" />
                    <div>
                        <h2 className="text-base font-bold text-[color:var(--foreground)]">
                            Setup Guide Preview
                        </h2>
                        <p className="text-xs text-[color:var(--muted-foreground)]">
                            Quick-start developer commands for local setup
                        </p>
                    </div>
                </div>

                <div className="space-y-2.5">
                    {setupCommands.map((item, idx) => (
                        <div
                            key={idx}
                            className="flex flex-col gap-2 rounded-2xl border border-[color:var(--border)] bg-[color:var(--background)] p-3 sm:flex-row sm:items-center sm:justify-between"
                        >
                            <div className="flex items-center gap-3 font-mono text-xs">
                                <span className="text-[color:var(--muted-foreground)]">$</span>
                                <span className="font-semibold text-[color:var(--foreground)]">
                                    {item.cmd}
                                </span>
                                <span className="hidden text-[11px] text-[color:var(--muted-foreground)] sm:inline">
                                    — {item.label}
                                </span>
                            </div>

                            <button
                                type="button"
                                onClick={() => copyToClipboard(item.cmd, idx)}
                                className="inline-flex items-center gap-1.5 self-end rounded-lg border border-[color:var(--border)] bg-[var(--card)] px-3 py-1.5 text-xs font-semibold text-[color:var(--foreground)] transition hover:border-[var(--primary)] hover:text-[var(--primary)] sm:self-auto"
                            >
                                {copiedIndex === idx ? (
                                    <>
                                        <Check size={13} className="text-emerald-500" />
                                        <span className="text-emerald-500">Copied</span>
                                    </>
                                ) : (
                                    <>
                                        <Copy size={13} />
                                        <span>Copy</span>
                                    </>
                                )}
                            </button>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
