"use client";

import { useMemo, useState } from "react";
import { Unlock, ShieldCheck } from "lucide-react";
import { uploadAndDownloadFile } from "@/lib/apiClient";
import PdfToolLayout from "@/components/pdf/PdfToolLayout";
import PdfToolHero from "@/components/pdf/PdfToolHero";
import PdfFeatures from "@/components/pdf/PdfFeatures";
import PdfActionButton from "@/components/pdf/PdfActionButton";
import PdfUploader from "@/components/pdf/PdfUploader";
import PdfFileInfo from "@/components/pdf/PdfFileInfo";

function formatMB(bytes: number) {
    return (bytes / 1024 / 1024).toFixed(2);
}

export default function UnlockPdfPage() {
    const [file, setFile] = useState<File | null>(null);
    const [password, setPassword] = useState("");
    const [isProcessing, setIsProcessing] = useState(false);
    const [success, setSuccess] = useState(false);

    const onDrop = async (acceptedFiles: File[]) => {
        if (acceptedFiles.length === 0) return;
        setFile(acceptedFiles[0]);
        setSuccess(false);
    };

    const fileExtractedSize = useMemo(() => {
        if (!file) return "0.00";
        return formatMB(file.size);
    }, [file]);

    const handleUnlockProcessing = async () => {
        if (!file || !password) return;

        try {
            setIsProcessing(true);
            setSuccess(false);

            const formData = new FormData();
            formData.append("file", file);
            formData.append("password", password);

            await uploadAndDownloadFile("/security/unlock", formData, `${file.name.replace(/\.pdf$/i, "")}-unlocked.pdf`);

            setSuccess(true);
            setPassword("");
        } catch (err) {
            console.error(err);
            alert(err instanceof Error ? err.message : "Security domain transaction failed.");
        } finally {
            setIsProcessing(false);
        }
    };

    return (
        <PdfToolLayout>
            <PdfToolHero
                title="Unlock PDF"
                description="Strip protection limits, passwords, and security encryption blocks instantly from your documents using our specialized binary processing engine."
            />
            <div className="mt-12 rounded-3xl border border-[color:var(--border)] bg-[var(--card)] p-8 shadow-lg">
                <PdfUploader
                    onFilesAccepted={onDrop}
                    title="Upload Password Protected PDF"
                    description="Drop your encrypted document here to remove restrictions"
                />
                {file && (
                    <div className="mt-8 space-y-6">
                        <PdfFileInfo file={file} />
                        <div className="rounded-2xl border border-[color:var(--border)] p-5">
                            <h3 className="text-lg font-semibold flex items-center gap-2">
                                <Unlock size={18} className="text-indigo-500" /> Security Access Verification
                            </h3>
                            <div className="mt-4">
                                <label className="text-sm font-medium text-[color:var(--muted)]">
                                    Current Document Password
                                </label>
                                <input
                                    type="password"
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    placeholder="Enter the password to decrypt the file"
                                    className="mt-2 w-full rounded-xl border border-[color:var(--border)] bg-transparent p-3 text-sm outline-none transition focus:border-indigo-500"
                                />
                            </div>
                        </div>
                        <div className="rounded-2xl border border-[color:var(--border)] p-4">
                            <p className="text-sm text-[color:var(--muted)]">Target document footprint</p>
                            <p className="mt-1 text-2xl font-bold">{fileExtractedSize} MB</p>
                        </div>
                        {success && (
                            <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-5 text-emerald-900 dark:text-emerald-200 flex items-start gap-3">
                                <ShieldCheck className="text-emerald-500 mt-0.5 shrink-0" size={18} />
                                <div>
                                    <p className="text-sm font-semibold">Security restrictions dropped successfully!</p>
                                    <p className="text-xs mt-1 text-emerald-800/80 dark:text-emerald-200/70">
                                        The unlocked binary version was generated by the Go engine and downloaded to your machine.
                                    </p>
                                </div>
                            </div>
                        )}
                        <PdfActionButton
                            text="Remove Security and Unlock PDF"
                            loadingText="Executing Cipher Decryption..."
                            loading={isProcessing}
                            disabled={!password}
                            onClick={handleUnlockProcessing}
                        />
                    </div>
                )}
            </div>
            <PdfFeatures />
        </PdfToolLayout>
    );
}